In [1]:
#==============================================================================
# First step to write the python program is to take benefit out of libraries
# already available. We will only focus on the data science related libraries.
#==============================================================================
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#==============================================================================
# #import data from the data file. In our case its Health.csv. 
#==============================================================================

healthData = pd.read_csv ('Health.csv')
healthData.shape

(9, 4)

In [3]:
healthData

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     Asian        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes

In [4]:
healthData.head(2)

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No

In [6]:
healthData.isnull().sum()

Ethnicity               0
Height (CM)             1
Weight (Kg)             1
Will survive till 70    0
dtype: int64

In [7]:
np.mean(healthData['Height (CM)'])

180.0

In [8]:
healthData['Height (CM)'] = healthData['Height (CM)'].fillna(np.mean(healthData['Height (CM)']))
healthData['Weight (Kg)'] = healthData['Weight (Kg)'].fillna(np.mean(healthData['Weight (Kg)']))

In [9]:
healthData.isnull().sum()

Ethnicity               0
Height (CM)             0
Weight (Kg)             0
Will survive till 70    0
dtype: int64

In [10]:
#==============================================================================
# All mathematical operations will be performed on the matrix, so now we create
# matrix for dependent variables and independent variables.
#==============================================================================

X = healthData.iloc [:,:-1].values
y = healthData.iloc [:,3].values

In [11]:
X

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['Asian', 175.0, 80.0],
       ['White', 180.0, 88.0],
       ['Asian', 178.0, 85.25],
       ['Asian', 172.0, 72.0],
       ['African', 178.0, 75.0],
       ['White', 180.0, 89.0],
       ['African', 186.0, 90.0]], dtype=object)

In [12]:
y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [13]:
#==============================================================================
# Encode the categorial data. So now instead of character values we will have
# corresponding numerical values
#==============================================================================

from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X[:, 0] = X_labelencoder.fit_transform(X[:, 0])
print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [1 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 85.25]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 180.0 89.0]
 [0 186.0 90.0]]
[1 0 0 1 0 1 0 1 1]


In [14]:
#==============================================================================
# Implementing OneHotEncoder to separate category variables into dummy 
# variables.
#==============================================================================

from sklearn.preprocessing import OneHotEncoder
X_onehotencoder = OneHotEncoder (categorical_features = [0])
X = X_onehotencoder.fit_transform(X).toarray()
print (X)

[[   0.      0.      1.    186.     90.  ]
 [   1.      0.      0.    185.     98.  ]
 [   0.      1.      0.    175.     80.  ]
 [   0.      0.      1.    180.     88.  ]
 [   0.      1.      0.    178.     85.25]
 [   0.      1.      0.    172.     72.  ]
 [   1.      0.      0.    178.     75.  ]
 [   0.      0.      1.    180.     89.  ]
 [   1.      0.      0.    186.     90.  ]]


In [22]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, 
                                                     random_state = 0)


c:\users\aayushi\python36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [23]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, 
                                                     random_state = 0)


In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7, 5)
(2, 5)
(7,)
(2,)


In [25]:
#==============================================================================
# Feature scaling is to bring all the independent variables in a dataset into
# same scale, to avoid any variable dominating  the model. Here we will not 
# transform the dependent variables.
#==============================================================================

from sklearn.preprocessing import StandardScaler
independent_scalar = StandardScaler()
X_train = independent_scalar.fit_transform (X_train) #fit and transform
X_test = independent_scalar.transform (X_test) # only transform
print(X_train)

[[ 1.15470054 -0.63245553 -0.63245553  0.88159065  1.48988518]
 [-0.8660254   1.58113883 -0.63245553 -0.55834074 -0.02546812]
 [ 1.15470054 -0.63245553 -0.63245553  1.08729513  0.53907526]
 [ 1.15470054 -0.63245553 -0.63245553 -0.55834074 -1.24369333]
 [-0.8660254  -0.63245553  1.58113883 -0.14693177  0.30137279]
 [-0.8660254  -0.63245553  1.58113883  1.08729513  0.53907526]
 [-0.8660254   1.58113883 -0.63245553 -1.79256765 -1.60024704]]


In [26]:
print(X_test)

[[-0.8660254  -0.63245553  1.58113883 -0.14693177  0.42022402]
 [-0.8660254   1.58113883 -0.63245553 -1.1754542  -0.64943713]]
